### ISSUE TITLE
firestore.Documents.Next: rpc error: code = FailedPrecondition desc = The query requires an index.

### ISSUE THREAD

**Issue by maengsanha** [CONCAT-internship/smartfarmer-arduino#10]
- error message

```
Function panic: runtime error: invalid memory address or nil pointer dereference

goroutine 22 [running]:
runtime/debug.Stack(0xc0001172e0, 0x9af340, 0xf4ab40)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/GoogleCloudPlatform/functions-framework-go/funcframework.registerHTTPFunction.func1.1(0xb504a0, 0xc0002e4000)
	/layers/google.go.gomod/gopath/pkg/mod/github.com/!google!cloud!platform/functions-framework-go@v1.0.1/funcframework/framework.go:73 +0x57
panic(0x9af340, 0xf4ab40)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
cloud.google.com/go/firestore.(*DocumentSnapshot).Exists(...)
	/layers/google.go.gomod/gopath/pkg/mod/cloud.google.com/go/firestore@v1.2.0/document.go:58
cloud.google.com/go/firestore.(*DocumentSnapshot).DataTo(0x0, 0x9b28a0, 0xc00032c000, 0x1c, 0xc000117768)
	/layers/google.go.gomod/gopath/pkg/mod/cloud.google.com/go/firestore@v1.2.0/document.go:112 +0x37
github.com/CONCAT-internship/smartfarmer/src/cloud/functions.Get(0xb504a0, 0xc0002e4000, 0xc0000ee500)
	/workspace/serverless_function_source_code/get.go:64 +0x67d
github.com/GoogleCloudPlatform/functions-framework-go/funcframework.registerHTTPFunction.func1(0xb504a0, 0xc0002e4000, 0xc0000ee500)
	/layers/google.go.gomod/gopath/pkg/mod/github.com/!google!cloud!platform/functions-framework-go@v1.0.1/funcframework/framework.go:76 +0x163
net/http.HandlerFunc.ServeHTTP(0xc0001b4a30, 0xb504a0, 0xc0002e4000, 0xc0000ee500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xf5f8a0, 0xb504a0, 0xc0002e4000, 0xc0000ee500)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0002c0000, 0xb504a0, 0xc0002e4000, 0xc0000ee500)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00027c6e0, 0xb518a0, 0xc000082f40)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
```

- 쿼리가 잘못되어 일어난 것으로 추정됨. Get 함수 수정 후 재배포 필요

**Comment by maengsanha** [comment]
테스트 함수 작성 후 배포하여 테스트해본 결과, `.where.orderBy`는 성공함.
`.where.orderBy.where`를 해야할 것으로 추정

**Comment by maengsanha** [comment]
Resolved by above method.<br>Create merge pull request.
